Json5
====

The thing about Json is that it's hard to document - without comments you can only see the what, not the why. You could use "description" fields, but that's not very discoverable.

Thank goodness for Json5!

Json5 is a superset of JSON that allows for comments and trailing commas. It's a popular choice for configuration files due to its readability and flexibility.

From the web site:

> Formally, the JSON5 Data Interchange Format is a superset of JSON (so valid JSON files will always be valid JSON5 files) that expands its syntax to include some productions from ECMAScript 5.1 (ES5). It's also a subset of ES5, so valid JSON5 files will always be valid ES5.*

Read more about Json5 here: https://json5.org/

The main reason I'm using Json5 is to

- allow for comments
- allow for trailing commas
- avoid quoting property names - making it easy to use in JavaScript or TypeScript

Lets take a simple Json file:

.sample.json
[source,json]
----
include::sample.json[]
----

And convert it to Json5:

.sample-without-comments.json5
[source,json5]
----
include::sample-without-comments.json5[]
----

Let's bling it up with comments so we can explain what's going on:

.sample.json5
[source,json5]
----
include::sample.json5[]
----

Now lets pretend the snippet originated in a TypeScript or JavaScript file - we can copy it to a Json5 file without modification -
the point being that we can easily copy from code into configuration without having to convert to Json format - eg quoting the property names:

.sample-typescript-json5.ts
[source,ts]
----
include::sample-typescript-json5.ts[]
----

== How to use it

You can use Json5 in your JavaScript or TypeScript code like this:
```
npm install json5
import JSON5 from 'json5'
const data = JSON5.parse(json5String)
JSON5.stringify(data)
```

To convert Json5 to Json use the cli:

```
npm install --global json5
json5 --out-file sample.json sample.json5
json5 --validate sample.json5
```

In Kotlin there is the json5k library: https://github.com/xn32/json5k

```
Json5.decodeFromString<Person>("{ name: 'Carl', age: 42 }") // Person(name=Carl, age=42)
Json5.encodeToString(Person("John", 31u)) // {name:"John",age:31}
```

